name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
    -
      name: Check out repository
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: false
        registry-url: https://registry.npmjs.org
        cache: 'npm'
        cache-dependency-path: package-lock.json
    -
      name: Install dependencies
      run: |
        npm cache verify
        npm ci --prefer-offline --no-audit --no-optional --ignore-scripts

    -
      name: Build
      run: npm run build --if-present

    -
      name: Audit
      run: npm audit --audit-level=moderate
